services:
  db-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "costam@711"
      ACCEPT_EULA: "Y"
    volumes:
      - ./data/db:/usr/app/data
      - ./../sql:/tmp/sql
    command: /bin/bash /tmp/sql/entrypoint.sh
  password-hash-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: password-hash-server
    ports:
      - "1444:1433"
    environment:
      SA_PASSWORD: "costam@711"
      ACCEPT_EULA: "Y"
    volumes:
      - ./data/password-hash/db:/usr/app/data
      - ./../sql:/tmp/sql
    command: /bin/bash /tmp/sql/password-hash-entrypoint.sh
  password-salt-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: password-salt-server
    ports:
      - "1455:1433"
    environment:
      SA_PASSWORD: "costam@711"
      ACCEPT_EULA: "Y"
    volumes:
      - ./data/password-salt/db:/usr/app/data
      - ./../sql:/tmp/sql
    command: /bin/bash /tmp/sql/password-salt-entrypoint.sh
  web-app:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: web-app
    networks: 
      - tickor_network
    ports:
      - 3000:3000
    volumes:
      - ./..:/opt/project
      - /opt/project/docker
      - ./data/app:/tmp/tocker_local_storage
  #   depends_on:
  #     - db-server
  #   tty: true
networks:
  tickor_network:
    name: tickor_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.96.0/24